package src.command;

public enum CommandType {
    ADD_DATABASE,
    ADD_MANUALLY,
    REMOVE,
    EDIT_SERIES_TITLE,
    EDIT_STORY_TITLE,
    EDIT_PUBLISHER,
    EDIT_DESCRIPTION,
    EDIT_VOLUMENUMBER,
    EDIT_ISSUENUMBER,
    EDIT_PUBLICATION_DATE,
    EDIT_CREATOR,
    EDIT_VALUE,
    EDIT_GRADE,
    EDIT_SLAB,
    EDIT_AUTHENTICATED,
    EDIT_SIGNATURES
}
